version: '3.4'

services: 
    typesense:
        restart: unless-stopped
        image: typesense/typesense:0.20.0
        container_name: typesense-container
        environment:
           TYPESENSE_DATA_DIR: /data
           TYPESENSE_API_KEY: typesensekey
        volumes:
          - search-data:/data
        ports: 
            - 8108:8108
volumes: 
    search-data:
        driver: local